title: Sai Vivek Kurapati
tagline: Electrical Engineering Student | Robotics Enthusiast | Maker
description: My personal portfolio and blog featuring projects, academic work, and contact information.
url: "https://ksvivek25.github.io"  # your GitHub Pages URL
baseurl: ""  # leave this blank if your repo is username.github.io
email: kurapatisvivek@outlook.com
github: ksvivek25  
linkedin: https://www.linkedin.com/in/saivivekkurapati/
author:
  name: Sai Vivek Kurapati
  bio: Electrical Engineering undergrad passionate about robotics, automation, and embedded systems.
  location: Denton, Texas
theme_mode: dark  # or light, or auto
paginate: 5  # number of posts per page
footer:
  links:
    - label: Resume
      url: /resume.pdf
