# === Portfolio Configuration for Angela Chuah ===

# Theme
theme: jekyll-theme-chirpy

# Language and Timezone
lang: en
timezone: Asia/Kuala_Lumpur

# Site Identity
title: Angela Chuah
tagline: AI Student | Flutter Developer | Dream Chaser
description: >-
  A portfolio to showcase my work in AI, websites, mobile apps, university assignments, and more.

url: "https://acxy_official.github.io"
baseurl: ""

# Social & Author Info
github:
  username: Seriously88

social:
  name: Angela Chuah Xin Yi
  email: acxy.official@outlook.com
  links:
    - https://github.com/Seriously88
    - https://www.linkedin.com/in/angelacxy

# SEO Site Verification (leave blank if not using)
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics (optional – leave blank or use your tracking ID)
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page Views (optional – leave blank or add goatcounter ID)
pageviews:
  provider:

# Theme Mode: auto = user's system | light | dark
theme_mode: dark

# Avatar (optional: can upload image to assets/img/avatar.png)
avatar: /assets/img/avatar.png

# Preview image for link sharing
social_preview_image:

# TOC in posts
toc: true

# Comments (leave blank if not using)
comments:
  provider:

# PWA (Offline availability)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# Pagination
paginate: 10

# Assets CDN (skip unless you're using a CDN)
cdn:

# === Advanced Settings (Leave default unless needed) ===
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
